# Prometheus configuration
prometheus:
  prometheusSpec:
    storageSpec:
      emptyDir: {}
    resources:
      requests:
        memory: "500Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    retention: "1d"

# Alertmanager configuration
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      emptyDir: {}
    replicas: 1
    config:
      global:
        resolve_timeout: 5m
      route:
        receiver: "default-receiver"
        group_by: ['job']
        group_wait: 10s
        group_interval: 5m
        repeat_interval: 1h  # Shortened repeat interval
      receivers:
        - name: "default-receiver"
          email_configs:
            - to: "your-email@example.com"  # Use your email here
              from: "alertmanager@example.com"
              smarthost: "smtp.example.com:587"  # Your SMTP configuration
              auth_username: "your-username"
              auth_password: "your-password"
      inhibit_rules:
        - source_match:
            severity: 'critical'
          target_match:
            severity: 'warning'
          equal: ['alertname', 'namespace', 'instance']

# Grafana configuration
grafana:
  enabled: true
  adminPassword: "admin"
  persistence:
    enabled: false
  ingress:
    enabled: false
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "400Mi"
      cpu: "200m"
  sidecar:
    datasources:
      enabled: true

# Prometheus Operator
prometheusOperator:
  createCustomResource: true
  admissionWebhooks:
    enabled: false

# Node exporter (optional, enables monitoring of Minikube node)
nodeExporter:
  enabled: true

# Kube State Metrics (for Kubernetes-specific metrics)
kubeStateMetrics:
  enabled: true
