apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-project
  labels:
    app: fast-api-project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fast-api-project
  template:
    metadata:
      name: fast-api-project
      labels:
        app: fast-api-project
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value : postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
        - name: fast-api-project
          image: anasch07/gl5-mini-project-devops
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      