line-length = 120
exclude = ["alembic/versions/*.py", "alembic/env.py"]

select = [
    "E",    # pycodestyle
    "W",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP"    # pyupgrade
]
ignore = []

[per-file-ignores]
"alembic/versions/*.py" = ["ALL"]
"alembic/env.py" = ["ALL"]