line-length = 120

select = [
    "E",    # pycodestyle
    "W",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP"    # pyupgrade
]

ignore = []

[per-file-ignores]
"__init__.py" = ["F401"]
