name: Lint, Format, Test, and Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format-test-build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          cd fastapi-docker-app
          poetry install

      - name: Format code with ruff
        run: |
          cd fastapi-docker-app
          poetry run ruff . --fix  # Automatically fix issues

      - name: Lint code with ruff
        continue-on-error: true  # Allow linting to fail without blocking the workflow
        run: |
          cd fastapi-docker-app
          poetry run ruff .  # Run lint without auto-fixing

      - name: Run tests
        run: |
          cd fastapi-docker-app
          poetry run pytest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fastapi-docker-app
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/gl5-mini-project-devops:latest
