name: Lint, Format, Test, Scan, Build, and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          cd fastapi-docker-app
          poetry install

      - name: Lint code with ruff
        run: |
          cd fastapi-docker-app
          poetry run ruff .

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          cd fastapi-docker-app
          poetry install

      - name: Format code with ruff
        run: |
          cd fastapi-docker-app
          poetry run ruff . --fix

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry pytest-cov
          cd fastapi-docker-app
          poetry install

      - name: Run tests and generate coverage report
        run: |
          cd fastapi-docker-app
          poetry run pytest --cov=app --cov-report=xml --cov-report=term-missing

      - name: Upload coverage report for later steps
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: fastapi-docker-app/coverage.xml

  trivy-scan:
    needs: [lint, format, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy to scan source code
        run: |
          trivy fs ./fastapi-docker-app \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            --ignore-unfixed \
            --format table

  sonarQube:
    needs: trivy-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: .

      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build:
    needs: sonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fastapi-docker-app
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gl5-mini-project-devops:latest
          push: false

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fastapi-docker-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gl5-mini-project-devops:latest